### ISSUE TITLE
Some Concerns Regarding the Tables

### ISSUE THREAD

**Issue by gelarehhaselmehri** [SchizoBoy/dataset_generation#2]
1. **ObjectID** in first table is expected to be the same variable as **Object** in the second table. 
https://github.com/SchizoBoy/dataset_generation/blob/2e88b8c2024209643a89905d31884457a5ce56df/EXAMPLE/ds_mark1.ds#L6
&
https://github.com/SchizoBoy/dataset_generation/blob/2e88b8c2024209643a89905d31884457a5ce56df/EXAMPLE/ds_mark1.ds#L17

2. The same holds for **Controller** in the first and the third tables.

**Comment by 3C4D** [comment]
Indeed the first table was wrong thanks, however I don't catch your second concern.

In the first table the object's controller is random, chosen in the range {1, 4} (assuming we have 4 possible controllers)
In the third table, all the controllers need to have his own line so there are 4 of them.

Let me know if I am wrong.

**Comment by Gelarehh** [comment]
You are right regarding the second table. It will be only the first table then.
I am going to keep the issue open in case I had other questions.

**Comment by gelarehhaselmehri** [comment]
1. You are right about table 3.

2. I think the structure of table 1 needs to be changed. The idea is to have the sensitivity that _each_ controller corresponds to _each_ object. (Currently, table 1 is giving the sensitivity level for only four ObjectID-Controller pairs.)
To get what we want, you can put fixed values for both ObjectID _(on rows)_ and Controller _(on columns)_:
`{ObjectID, fixed, {1, 2, 3, 4, 5}}` (for 5 objects, for instance)
`{Controller, fixed, {1, 2, 3, 4}}` (for 4 controllers, for instance)
Then fill the 5by4 table with Sensitivity values from a distribution:
`{Sensitivity, normal(2, 1), range(1, 3)}`

**Comment by 3C4D** [comment]
Ok then the sensitivity table could be a double entry table (type 2), like this

```
TABLE typ2 Sensitivity {
    lines : 4;
    columns : 5;
    symmetry : true;

    vectors : true;
    diagonal : empty;

    lines_top_values : {1, 2, 3, 4}; // or range(1, 4)
    columns_top_values : {1, 2, 3, 4, 5}; // or range(1, 5)
    distribution : {normal(2, 1), range(1, 3)};
  }
```

An example table would be :

```
 , 1, 2, 3, 4, 5
1, 2, 3, 1, 2, 3
2, 1, 2, 2, 3, 1
3, 3, 2, 1, 2, 2
4, 1, 3, 2, 2, 2
```

Here we can imagine the object ids are the column names and the controllers id are the names of the lines.
